Repository AY2425S1-CS2103T-T16-4/tp, pull requests merged in 2024-10, with the labels that each got.

#11 Add hugh's photo
  docs/images/gnoossk.png
Labels: priority.High, severity.High

#16 Update AboutUs
  docs/AboutUs.md
  docs/team/gnoossk.md
Labels: priority.Low

#30 Update README
  README.md
Labels: priority.High

#39 Add Use Cases in DG
  docs/DeveloperGuide.md
Labels: type.Task

#60 Add Student model
  docs/DeveloperGuide.md
  src/main/java/seedu/address/model/student/ContactNumber.java
  src/main/java/seedu/address/model/student/Name.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/StudentNumber.java
  src/main/java/seedu/address/model/student/TutorialGroup.java
  src/main/java/seedu/address/model/student/exceptions/DuplicateStudentException.java
  src/main/java/seedu/address/model/student/exceptions/StudentNotFoundException.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/student/ContactNumberTest.java
  src/test/java/seedu/address/model/student/NameTest.java
  src/test/java/seedu/address/model/student/StudentNumberTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
  src/test/java/seedu/address/model/student/TutorialGroupTest.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: priority.High

#64 Finish week 8
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/CommandResult.java
Labels: severity.Low

#73 Add Delete Student Command
  src/main/java/seedu/address/logic/commands/DeleteStudentCommand.java
Labels: priority.High

#63 Branch add student details
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddStudentCommand.java
  src/main/java/seedu/address/logic/parser/AddStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/address/logic/parser/AddStudentCommandParserTest.java
Labels: priority.High

#84 Add proper Message Usage format for MarkAttendanceCommand
  src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/address/logic/parser/MarkAttendanceCommandParser.java
Labels: priority.Medium

#80 Implement basic student GUI
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddStudentCommand.java
  src/main/java/seedu/address/model/assignment/Assignment.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/StudentNumber.java
  src/main/java/seedu/address/model/student/TutorialGroup.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/java/seedu/address/ui/StudentListPanel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/TT_icon.png
  src/main/resources/images/default_student_image.png
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StudentListCard.fxml
  src/main/resources/view/StudentListPanel.fxml
Labels: priority.Medium, severity.Low

#91 Update list command
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
Labels: priority.High, severity.High

#78 Complete DeleteStudentCommand
  src/main/java/seedu/address/logic/commands/DeleteStudentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteAssignmentCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteStudentCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/resources/view/StudentListCard.fxml
  src/test/java/seedu/address/logic/commands/DeleteStudentCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteStudentCommandParserTest.java
Labels: priority.High

#103 Fix Grade Regex Bug with Storage
  src/main/java/seedu/address/model/assignment/Grade.java
Labels: type.Bug

#96 Add command to delete duplicate name students
  src/main/java/seedu/address/logic/commands/DeleteStudentCommand.java
  src/main/java/seedu/address/logic/parser/DeleteStudentCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteStudentCommandTest.java
Labels: priority.Medium

#113 Polish delete command
  src/main/java/seedu/address/logic/commands/DeleteAssignmentCommand.java
  src/main/java/seedu/address/logic/parser/DeleteAssignmentCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/assignment/AssignmentName.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkAttendanceCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteAssignmentCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.Low

#116 Integrate attendance storage
  docs/UserGuide.md
  docs/diagrams/StorageClassDiagram.puml
  src/main/java/seedu/address/logic/commands/GetAttendanceByTgCommand.java
  src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/address/model/attendance/AttendanceRecord.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/storage/attendance/JsonAdaptedAttendance.java
  src/main/java/seedu/address/storage/attendance/JsonAdaptedAttendanceRecord.java
  src/main/java/seedu/address/ui/AttendanceWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkAttendanceCommandTest.java
  src/test/java/seedu/address/model/attendance/AttendanceRecordTest.java
  src/test/java/seedu/address/storage/JsonAdaptedAttendanceRecordTest.java
  src/test/java/seedu/address/storage/JsonAdaptedAttendanceTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: priority.High

#131 Add more tests
  addressbook.log-LAPTOP-K3J5V8U3.0
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/student/Student.java
  src/test/data/JsonSerializableStudentAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/EditStudentCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewStudentCommandTest.java
  src/test/java/seedu/address/logic/parser/AddStudentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteStudentCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
  src/test/java/seedu/address/ui/AttendanceWindowTest.java
Labels: priority.High

#142 Fix bug in undo deleteStudent
  src/main/java/seedu/address/logic/commands/DeleteStudentCommand.java
Labels: priority.High

#140 Change deletion of assignment
  src/main/java/seedu/address/logic/commands/AddAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAssignmentCommand.java
  src/main/java/seedu/address/logic/parser/DeleteAssignmentCommandParser.java
  src/main/java/seedu/address/model/student/Student.java
  src/test/java/seedu/address/logic/commands/DeleteAssignmentCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteAssignmentCommandParserTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
Labels: priority.High

#136 Undo markat
  src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/MarkPresentAllCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkPresentAllCommand.java
  src/main/java/seedu/address/model/student/Student.java
  src/test/java/seedu/address/logic/commands/MarkAttendanceCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkPresentAllCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkPresentAllCommandTest.java
Labels: priority.High

#159 Update Adds, Edits, Undo parts of the UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteAllStudentsCommandParser.java
  src/main/java/seedu/address/logic/parser/UndoCommandParser.java
  src/test/java/seedu/address/logic/parser/DeleteAllStudentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UndoCommandParserTest.java
Labels: priority.High, severity.Medium

#148 Basic cli controls
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandHistory.java
  src/main/java/seedu/address/logic/commands/CommandStack.java
  src/main/java/seedu/address/logic/commands/DeleteStudentCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandHistoryTest.java
  src/test/java/seedu/address/logic/commands/CommandStackTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
Labels: priority.Medium
